language: php
dist: trusty
php:
  - 7.0
  - nightly

before_script:
  - sudo apt-get update
  - sudo apt-get install libgtk-3-dev -y || sudo apt-cache search libgtk3
  - mkdir deps
  - mkdir deps/lib
  - mkdir deps/include
  - git clone https://github.com/andlabs/libui
  - cd libui
  - mkdir build
  - cd build
  - cmake .. -G "Unix Makefiles"
  - make -j4
  - cp out/libui.so ../../deps/lib
  - cp out/libui.so.0 ../../deps/lib
  - cp ../ui*.h ../../deps/include
  - cd ../../
 
script:
  - phpize
  - ./configure --with-ui=deps
  - make
  - REPORT_EXIT_STATUS=1 TEST_PHP_ARGS="-q --show-diff" make test
